title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "http://ideal.umd.edu"
baseurl: "http://ideal.umd.edu/d3-deadlines/"

twitter_hashtag: machinelearning
github_username: IDEALLab
github_repo: d3-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
